/** Bracketed segments that exist only to advertise the upload, not the song. */
const PROMO_NOISE =
  /\s*[([][^()[\]]*(?:official|video|audio|lyrics?|hd|hq|4k|8k|remaster(?:ed)?|mv|visuali[sz]er|full song)[^()[\]]*[)\]]/gi

const UNKNOWN_ARTIST = 'Desconocido'

export function playlistIdFromInput(input: string): string | null {
  const trimmed = input.trim()
  const fromUrl = /[?&]list=([^&]+)/.exec(trimmed)
  if (fromUrl) return fromUrl[1]
  return /^[A-Za-z0-9_-]{2,}$/.test(trimmed) && !trimmed.includes('/') ? trimmed : null
}

export function cleanTitle(raw: string): string {
  return raw.replace(PROMO_NOISE, ' ').replace(/\s+/g, ' ').trim()
}

/**
 * YouTube titles usually read "Artist - Title". When they do not, the channel
 * name is the next best guess ("Nirvana - Topic" is auto-generated by YouTube).
 */
export function splitArtistAndTitle(
  rawTitle: string,
  channelTitle: string,
): { artist: string; title: string } {
  const cleaned = cleanTitle(rawTitle)
  const dash = cleaned.indexOf(' - ')
  if (dash > 0) {
    return {
      artist: cleaned.slice(0, dash).trim(),
      title: cleaned.slice(dash + 3).trim(),
    }
  }
  const channel = channelTitle.replace(/\s*-\s*Topic$/i, '').trim()
  return { artist: channel || UNKNOWN_ARTIST, title: cleaned }
}

export function slugify(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // combining marks left behind by NFD
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}
